### ISSUE TITLE
Agregar y cambiar todo el proyecto dentro de un modelo MVC y Node.js

### ISSUE THREAD

**Issue by JPZC** [CarsOk/tjdatagroup#121]
## Yo como:
Usuario
## Quiero:
Que lo que haga sea guardado en una base de datos
## Para:
Que todo sea mas rapido y facil de elaborar

## Criterios de aceptación 
- [x] Debe tener los colores de la pagina principal
- [x] Debe estar bien organizado
- [x] Debe estar en un modelo MVC
- [x] Debe mantener todos los archivox
